// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcServer.proto

package cn.gasin.dfs.rpc.namenode.service;

public interface FetchEditLogRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.gasin.dfs.rpc.namenode.FetchEditLogRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string backupNodeId = 1;</code>
   * @return The backupNodeId.
   */
  java.lang.String getBackupNodeId();
  /**
   * <code>string backupNodeId = 1;</code>
   * @return The bytes for backupNodeId.
   */
  com.google.protobuf.ByteString
      getBackupNodeIdBytes();

  /**
   * <code>int64 expectStartTxId = 2;</code>
   * @return The expectStartTxId.
   */
  long getExpectStartTxId();

  /**
   * <code>int64 expectEndTxId = 3;</code>
   * @return The expectEndTxId.
   */
  long getExpectEndTxId();
}
