// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcServer.proto

package cn.gasin.dfs.rpc.namenode.service;

/**
 * Protobuf type {@code cn.gasin.dfs.rpc.namenode.FetchEditLogRequest}
 */
public final class FetchEditLogRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cn.gasin.dfs.rpc.namenode.FetchEditLogRequest)
    FetchEditLogRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FetchEditLogRequest.newBuilder() to construct.
  private FetchEditLogRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FetchEditLogRequest() {
    backupNodeId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FetchEditLogRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FetchEditLogRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            backupNodeId_ = s;
            break;
          }
          case 16: {

            expectStartTxId_ = input.readInt64();
            break;
          }
          case 24: {

            expectEndTxId_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.gasin.dfs.rpc.namenode.service.NameNodeServer.internal_static_cn_gasin_dfs_rpc_namenode_FetchEditLogRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.gasin.dfs.rpc.namenode.service.NameNodeServer.internal_static_cn_gasin_dfs_rpc_namenode_FetchEditLogRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.gasin.dfs.rpc.namenode.service.FetchEditLogRequest.class, cn.gasin.dfs.rpc.namenode.service.FetchEditLogRequest.Builder.class);
  }

  public static final int BACKUPNODEID_FIELD_NUMBER = 1;
  private volatile java.lang.Object backupNodeId_;
  /**
   * <code>string backupNodeId = 1;</code>
   * @return The backupNodeId.
   */
  @java.lang.Override
  public java.lang.String getBackupNodeId() {
    java.lang.Object ref = backupNodeId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      backupNodeId_ = s;
      return s;
    }
  }
  /**
   * <code>string backupNodeId = 1;</code>
   * @return The bytes for backupNodeId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBackupNodeIdBytes() {
    java.lang.Object ref = backupNodeId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      backupNodeId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXPECTSTARTTXID_FIELD_NUMBER = 2;
  private long expectStartTxId_;
  /**
   * <code>int64 expectStartTxId = 2;</code>
   * @return The expectStartTxId.
   */
  @java.lang.Override
  public long getExpectStartTxId() {
    return expectStartTxId_;
  }

  public static final int EXPECTENDTXID_FIELD_NUMBER = 3;
  private long expectEndTxId_;
  /**
   * <code>int64 expectEndTxId = 3;</code>
   * @return The expectEndTxId.
   */
  @java.lang.Override
  public long getExpectEndTxId() {
    return expectEndTxId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getBackupNodeIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, backupNodeId_);
    }
    if (expectStartTxId_ != 0L) {
      output.writeInt64(2, expectStartTxId_);
    }
    if (expectEndTxId_ != 0L) {
      output.writeInt64(3, expectEndTxId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getBackupNodeIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, backupNodeId_);
    }
    if (expectStartTxId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, expectStartTxId_);
    }
    if (expectEndTxId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, expectEndTxId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.gasin.dfs.rpc.namenode.service.FetchEditLogRequest)) {
      return super.equals(obj);
    }
    cn.gasin.dfs.rpc.namenode.service.FetchEditLogRequest other = (cn.gasin.dfs.rpc.namenode.service.FetchEditLogRequest) obj;

    if (!getBackupNodeId()
        .equals(other.getBackupNodeId())) return false;
    if (getExpectStartTxId()
        != other.getExpectStartTxId()) return false;
    if (getExpectEndTxId()
        != other.getExpectEndTxId()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BACKUPNODEID_FIELD_NUMBER;
    hash = (53 * hash) + getBackupNodeId().hashCode();
    hash = (37 * hash) + EXPECTSTARTTXID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getExpectStartTxId());
    hash = (37 * hash) + EXPECTENDTXID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getExpectEndTxId());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.gasin.dfs.rpc.namenode.service.FetchEditLogRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.gasin.dfs.rpc.namenode.service.FetchEditLogRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.gasin.dfs.rpc.namenode.service.FetchEditLogRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.gasin.dfs.rpc.namenode.service.FetchEditLogRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.gasin.dfs.rpc.namenode.service.FetchEditLogRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.gasin.dfs.rpc.namenode.service.FetchEditLogRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.gasin.dfs.rpc.namenode.service.FetchEditLogRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.gasin.dfs.rpc.namenode.service.FetchEditLogRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.gasin.dfs.rpc.namenode.service.FetchEditLogRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cn.gasin.dfs.rpc.namenode.service.FetchEditLogRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.gasin.dfs.rpc.namenode.service.FetchEditLogRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.gasin.dfs.rpc.namenode.service.FetchEditLogRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.gasin.dfs.rpc.namenode.service.FetchEditLogRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cn.gasin.dfs.rpc.namenode.FetchEditLogRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cn.gasin.dfs.rpc.namenode.FetchEditLogRequest)
      cn.gasin.dfs.rpc.namenode.service.FetchEditLogRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.gasin.dfs.rpc.namenode.service.NameNodeServer.internal_static_cn_gasin_dfs_rpc_namenode_FetchEditLogRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.gasin.dfs.rpc.namenode.service.NameNodeServer.internal_static_cn_gasin_dfs_rpc_namenode_FetchEditLogRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.gasin.dfs.rpc.namenode.service.FetchEditLogRequest.class, cn.gasin.dfs.rpc.namenode.service.FetchEditLogRequest.Builder.class);
    }

    // Construct using cn.gasin.dfs.rpc.namenode.service.FetchEditLogRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      backupNodeId_ = "";

      expectStartTxId_ = 0L;

      expectEndTxId_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.gasin.dfs.rpc.namenode.service.NameNodeServer.internal_static_cn_gasin_dfs_rpc_namenode_FetchEditLogRequest_descriptor;
    }

    @java.lang.Override
    public cn.gasin.dfs.rpc.namenode.service.FetchEditLogRequest getDefaultInstanceForType() {
      return cn.gasin.dfs.rpc.namenode.service.FetchEditLogRequest.getDefaultInstance();
    }

    @java.lang.Override
    public cn.gasin.dfs.rpc.namenode.service.FetchEditLogRequest build() {
      cn.gasin.dfs.rpc.namenode.service.FetchEditLogRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cn.gasin.dfs.rpc.namenode.service.FetchEditLogRequest buildPartial() {
      cn.gasin.dfs.rpc.namenode.service.FetchEditLogRequest result = new cn.gasin.dfs.rpc.namenode.service.FetchEditLogRequest(this);
      result.backupNodeId_ = backupNodeId_;
      result.expectStartTxId_ = expectStartTxId_;
      result.expectEndTxId_ = expectEndTxId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.gasin.dfs.rpc.namenode.service.FetchEditLogRequest) {
        return mergeFrom((cn.gasin.dfs.rpc.namenode.service.FetchEditLogRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.gasin.dfs.rpc.namenode.service.FetchEditLogRequest other) {
      if (other == cn.gasin.dfs.rpc.namenode.service.FetchEditLogRequest.getDefaultInstance()) return this;
      if (!other.getBackupNodeId().isEmpty()) {
        backupNodeId_ = other.backupNodeId_;
        onChanged();
      }
      if (other.getExpectStartTxId() != 0L) {
        setExpectStartTxId(other.getExpectStartTxId());
      }
      if (other.getExpectEndTxId() != 0L) {
        setExpectEndTxId(other.getExpectEndTxId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cn.gasin.dfs.rpc.namenode.service.FetchEditLogRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cn.gasin.dfs.rpc.namenode.service.FetchEditLogRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object backupNodeId_ = "";
    /**
     * <code>string backupNodeId = 1;</code>
     * @return The backupNodeId.
     */
    public java.lang.String getBackupNodeId() {
      java.lang.Object ref = backupNodeId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        backupNodeId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string backupNodeId = 1;</code>
     * @return The bytes for backupNodeId.
     */
    public com.google.protobuf.ByteString
        getBackupNodeIdBytes() {
      java.lang.Object ref = backupNodeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        backupNodeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string backupNodeId = 1;</code>
     * @param value The backupNodeId to set.
     * @return This builder for chaining.
     */
    public Builder setBackupNodeId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      backupNodeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string backupNodeId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBackupNodeId() {
      
      backupNodeId_ = getDefaultInstance().getBackupNodeId();
      onChanged();
      return this;
    }
    /**
     * <code>string backupNodeId = 1;</code>
     * @param value The bytes for backupNodeId to set.
     * @return This builder for chaining.
     */
    public Builder setBackupNodeIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      backupNodeId_ = value;
      onChanged();
      return this;
    }

    private long expectStartTxId_ ;
    /**
     * <code>int64 expectStartTxId = 2;</code>
     * @return The expectStartTxId.
     */
    @java.lang.Override
    public long getExpectStartTxId() {
      return expectStartTxId_;
    }
    /**
     * <code>int64 expectStartTxId = 2;</code>
     * @param value The expectStartTxId to set.
     * @return This builder for chaining.
     */
    public Builder setExpectStartTxId(long value) {
      
      expectStartTxId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 expectStartTxId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearExpectStartTxId() {
      
      expectStartTxId_ = 0L;
      onChanged();
      return this;
    }

    private long expectEndTxId_ ;
    /**
     * <code>int64 expectEndTxId = 3;</code>
     * @return The expectEndTxId.
     */
    @java.lang.Override
    public long getExpectEndTxId() {
      return expectEndTxId_;
    }
    /**
     * <code>int64 expectEndTxId = 3;</code>
     * @param value The expectEndTxId to set.
     * @return This builder for chaining.
     */
    public Builder setExpectEndTxId(long value) {
      
      expectEndTxId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 expectEndTxId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearExpectEndTxId() {
      
      expectEndTxId_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cn.gasin.dfs.rpc.namenode.FetchEditLogRequest)
  }

  // @@protoc_insertion_point(class_scope:cn.gasin.dfs.rpc.namenode.FetchEditLogRequest)
  private static final cn.gasin.dfs.rpc.namenode.service.FetchEditLogRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.gasin.dfs.rpc.namenode.service.FetchEditLogRequest();
  }

  public static cn.gasin.dfs.rpc.namenode.service.FetchEditLogRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FetchEditLogRequest>
      PARSER = new com.google.protobuf.AbstractParser<FetchEditLogRequest>() {
    @java.lang.Override
    public FetchEditLogRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FetchEditLogRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FetchEditLogRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FetchEditLogRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cn.gasin.dfs.rpc.namenode.service.FetchEditLogRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

