// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcServer.proto

package cn.gasin.dfs.rpc.namenode.service;

public interface HeartbeatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.gasin.dfs.rpc.namenode.HeartbeatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status = 1;</code>
   * @return The status.
   */
  int getStatus();
}
