// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcServer.proto

package cn.gasin.dfs.rpc.namenode.service;

public final class NameNodeServer {
  private NameNodeServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_gasin_dfs_rpc_namenode_RegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_gasin_dfs_rpc_namenode_RegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_gasin_dfs_rpc_namenode_HeartbeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_gasin_dfs_rpc_namenode_HeartbeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_gasin_dfs_rpc_namenode_RegisterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_gasin_dfs_rpc_namenode_RegisterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_gasin_dfs_rpc_namenode_HeartbeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_gasin_dfs_rpc_namenode_HeartbeatResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\027NameNodeRpcServer.proto\022\031cn.gasin.dfs." +
      "rpc.namenode\"=\n\017RegisterRequest\022\n\n\002ip\030\001 " +
      "\001(\t\022\014\n\004port\030\002 \001(\005\022\020\n\010hostname\030\003 \001(\t\">\n\020H" +
      "eartbeatRequest\022\n\n\002ip\030\001 \001(\t\022\014\n\004port\030\002 \001(" +
      "\005\022\020\n\010hostname\030\003 \001(\t\"\"\n\020RegisterResponse\022" +
      "\016\n\006status\030\001 \001(\005\"#\n\021HeartbeatResponse\022\016\n\006" +
      "status\030\001 \001(\0052\345\001\n\022ClusterMaintainAPI\022e\n\010r" +
      "egister\022*.cn.gasin.dfs.rpc.namenode.Regi" +
      "sterRequest\032+.cn.gasin.dfs.rpc.namenode." +
      "RegisterResponse\"\000\022h\n\theartbeat\022+.cn.gas" +
      "in.dfs.rpc.namenode.HeartbeatRequest\032,.c" +
      "n.gasin.dfs.rpc.namenode.HeartbeatRespon" +
      "se\"\000B5\n!cn.gasin.dfs.rpc.namenode.servic" +
      "eB\016NameNodeServerP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cn_gasin_dfs_rpc_namenode_RegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_gasin_dfs_rpc_namenode_RegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_gasin_dfs_rpc_namenode_RegisterRequest_descriptor,
        new String[] { "Ip", "Port", "Hostname", });
    internal_static_cn_gasin_dfs_rpc_namenode_HeartbeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cn_gasin_dfs_rpc_namenode_HeartbeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_gasin_dfs_rpc_namenode_HeartbeatRequest_descriptor,
        new String[] { "Ip", "Port", "Hostname", });
    internal_static_cn_gasin_dfs_rpc_namenode_RegisterResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_cn_gasin_dfs_rpc_namenode_RegisterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_gasin_dfs_rpc_namenode_RegisterResponse_descriptor,
        new String[] { "Status", });
    internal_static_cn_gasin_dfs_rpc_namenode_HeartbeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_cn_gasin_dfs_rpc_namenode_HeartbeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_gasin_dfs_rpc_namenode_HeartbeatResponse_descriptor,
        new String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
